### PR TITLE
Enhance Any Sequencer to hanle cases that some tasks skipped

### LINKED ISSUE #652: Any Sequencer hangs if some dependencies skipped and other all dependencies failed
/kind bug

**What steps did you take and what happened:**
Any Sequencer hangs if some dependencies skipped and other all dependencies failed .

For example, if Any Seqencer depends on 3 tasks, task1 and task2 and task3, task1 and task2 failed, but task3 skipped, the Any Seq will hang.

**What did you expect to happen:**
Any Sequencer should be exits since all dependencies failed or skipped.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jinchihe**
**Which issue is resolved by this Pull Request:** 
Resolves #652 

**Description of your changes:**

Enhance Any Sequencer to hanle cases that some tasks skipped. For example, Any Seq depends on task1 and task2, task1 failed and task2 skipped, the Any Seq will hangs. The pr is going to fix the issue.

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by jinchihe** [comment]
/assign @pugangxa 
would you please help to review? Thanks a lot.

/cc @fenglixa @Tomcli

**Comment by jinchihe** [comment]
Unit test:
```
Starting to watch taskrun or run for 'node-7d1c9821-5b8d-4bd3-968e-604a27964348,node-e972e59e-b3a8-432a-a346-289217b07cb1' and conditions in kfp-afa4c2b913f14c5aab70970b8ac17bec/pipeline-00000000-0000-0000-0000-000000000000-f9434.
All specified TaskRun(s) or Run(s) failed or skipped.
All the tasks or conditions to watch does not meet, skipping.
Wrote Skipped to file /tekton/results/status.

```

File: tekton-catalog/any-sequencer/cmd/root.go [hunk 1]
```diff
@@ -460,13 +460,80 @@ func watch(cmd *cobra.Command, args []string) {
...
 	var failedTasks []string
+	var skippedTasks []string
 	for failedTask := range failedTasksCh {
 		if !contains(failedTasks, failedTask) {
 			failedTasks = append(failedTasks, failedTask)
 		}
 		if len(failedTasks) >= len(tasks) {
 			fmt.Println("All specified TaskRun(s) or Run(s) failed.")
 			exitWithStatus(skippedStatus, 1)
+		} else {
```
Comment (pugangxa) [inline tekton-catalog/any-sequencer/cmd/root.go:471]: This code may never been touched when there's skipped task. For example, there's 2 tasks watched(a, b), a failed and after sometime b skipped. since there's no content in failedTasksCh when b skipped, there's no chance for the logic to run.

Comment (jinchihe) [reply tekton-catalog/any-sequencer/cmd/root.go:471]: Yes, you are right, that's my expected, if there is any skipped tasks, should be in logic in the below changes to exit.
```
			if len(failedTasks)+len(skippedTasks) >= len(tasks) {
				fmt.Println("All specified TaskRun(s) or Run(s) failed or skipped.")
				exitWithStatus(skippedStatus, 1)
			}
```

Comment (jinchihe) [reply tekton-catalog/any-sequencer/cmd/root.go:471]: Yeah, great catch! Thanks @pugangxa

**Comment by jinchihe** [comment]
@pugangxa Your comment is addressed, ready for another look, thanks.

File: tekton-catalog/any-sequencer/cmd/root.go [hunk 2]
```diff
@@ -418,6 +433,46 @@ func watchRun(labelSelector string, tasks []string, failedTasksCh chan string) {
 	}
 }
 
+func watchSkippedTasks(fieldSelector string, tasks []string, skippedTasksCh chan string) []string {
```
Comment (pugangxa) [inline tekton-catalog/any-sequencer/cmd/root.go:436]: I'm not sure but since we already watched pr, can we get the run status/tr status from it to reduce use multiple watches. 
Also I saw the code said 
```
        // list of tasks that were skipped due to when expressions evaluating to false
	// +optional
	SkippedTasks []SkippedTask json:"skippedTasks,omitempty"
```
So I'm not sure whether it's only for "when" but not for task failed. If it's this case then if tekton wait all running task done then it will not done.

Anyway it's good now, please just try these cases, thanks.

Comment (jinchihe) [reply tekton-catalog/any-sequencer/cmd/root.go]: @pugangxa Great comments, yeah, we should only use pipelinerun watcher. Updated, pls take a another look, thanks.

**Comment by pugangxa** [comment]
Thanks Jinchi. It's fine to me now. Please help update markdown link to pass the test.
