### PR TITLE
fix(pipelineloop): Nested call stack depth limit

### LINKED ISSUE #775: Pipelineloop need to set maximum recursion stack in order to prevent endless loops that crashes the api-server
/kind bug

**What steps did you take and what happened:**
In recursion, there could be endless loops that creates too many pipelinerun and crashes the api-server in the master node. We need to set a maximum recursion stack to prevent this.

**What did you expect to happen:**

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by ScrapCodes**
**Which issue is resolved by this Pull Request:** 
Resolves #775

**Description of your changes:**
How to configure:

```
apiVersion: custom.tekton.dev/v1alpha1
kind: PipelineLoop
metadata:
  name: pipelineloop
  annotations:
    maxNestedStackDepth: "10"
spec:
```
**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

File: tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go [hunk 1]
```diff
@@ -78,6 +78,10 @@ const (
 
 	// LabelKeyWorkflowRunId is the label identifier a pipelinerun is managed by the Kubeflow Pipeline persistent agent.
 	LabelKeyWorkflowRunId = "pipeline/runid"
+
+	DefaultNestedStackDepth = 100
```
Comment (Tomcli) [inline tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go:82]: Can we set the `DefaultNestedStackDepth` to 30? I do realize when we have more than 30 stack, the k8s api-server start getting very slow.

Comment (ScrapCodes) [reply tekton-catalog/pipeline-loops/pkg/reconciler/pipelinelooprun/pipelinelooprun.go:82]: Yes, it was my guess. Thanks for clarifying the number.
