### PR TITLE
fix(ui, backend) Add pipelineRun to cache to assist in finding artifact data

### LINKED ISSUE #511: Artifact paths for cached tasks are incorrect
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Artifact paths for tasks which utilize the caching feature by adding `pipelines.kubeflow.org/cache_enabled: 'true'` label are incorrect. These artifact paths use current pipeline ID rather than the cached pipeline ID.

Screen Shot 2021-03-24 at 2 11 12 PM

**What did you expect to happen:**
 The artifact paths use the cached pipeline ID.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

* Python Version (use `python --version`):
* SDK Version: 
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by drewbutlerbb4**
**Which issue is resolved by this Pull Request:** 
Resolves #511

**Description of your changes:**
Update the cache server to store the ID of the pipelineRun that is being cached, mutate a metadata label of any pod that is getting mutated by the cache server with the ID of the pipelineRun of the pod that is cached.

The UI checks all pods to see if any were mutated and if they were the UI takes the pipelineRun ID from the mutated metadata label to use in any artifact paths that are listed.

**Environment tested:**

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

File: backend/src/cache/server/mutation.go [hunk 1]
```diff
@@ -248,7 +252,15 @@ func prepareInitContainer(pod *corev1.Pod, logger *zap.SugaredLogger) ([]corev1.
 
 func prepareMainContainer(pod *corev1.Pod, result string, logger *zap.SugaredLogger) ([]corev1.Container, error) {
 	logger.Infof("Start to prepare dummy containers.")
-	dummyContainers := []corev1.Container{}
+	image := "gcr.io/google-containers/busybox"
+	dummyContainer := corev1.Container{
```
Comment (Tomcli) [inline backend/src/cache/server/mutation.go:256]: Can we not add this extra container here? Here you are running two containers even though it's a cached task.

Maybe you can prepend the echo commands to the `replacedArg`  below. This way we only need to run one dummy container.

File: frontend/src/lib/WorkflowParser.ts [hunk 2]
```diff
@@ -376,7 +377,7 @@ export default class WorkflowParser {
     // Get the task name that corresponds to the nodeId
     let taskName = '';
     let taskStatus: NodePhase = NodePhase.SUCCEEDED;
-    for (const taskRunId of Object.getOwnPropertyNames(workflow.status.taskRuns || {})) {
+    for (const taskRunId of Object.getOwnPropertyNames(workflow.status.taskRuns)) {
```
Comment (Tomcli) [inline frontend/src/lib/WorkflowParser.ts:380]: Custom task is not a taskRuns, I remember this will break the custom task node in the previous PR.

File: backend/src/cache/server/mutation.go (hunk 1 above)
Comment (Tomcli) [reply backend/src/cache/server/mutation.go:256]: @drewbutlerbb4 please also update this test case with your new changes. Thanks
https://github.com/kubeflow/kfp-tekton/blob/master/backend/src/cache/server/mutation_test.go#L54-L63

Comment (Tomcli) [reply backend/src/cache/server/mutation.go:256]: `make run-cacheserver-unittests` will verify the cache server tests for you.

File: backend/src/cache/server/mutation.go [hunk 3]
```diff
@@ -257,6 +261,7 @@ func prepareMainContainer(pod *corev1.Pod, result string, logger *zap.SugaredLog
 	}
 
 	args := []string{}
+	args = append(args, "printf 'This step output is taken from cache.'")
```
Comment (Tomcli) [inline backend/src/cache/server/mutation.go:264]: Since we are using printf, break two new lines so this message is separate from the cached string.

```suggestion
	args = append(args, "printf 'This step output is taken from cache.\n\n'")
```

File: backend/src/cache/server/mutation_test.go [hunk 4]
```diff
@@ -57,7 +57,7 @@ var (
 					Name:    "main",
 					Image:   "test_image",
 					Command: []string{"python"},
-					Args:    []string{"-entrypoint", "/bin/bash", "--", "-c", "printf '200'"},
+					Args:    []string{"-entrypoint", "/bin/bash", "--", "-c", "printf 'This step output is taken from cache.'", "printf '200'"},
```
Comment (Tomcli) [inline backend/src/cache/server/mutation_test.go:60]:
```suggestion
					Args:    []string{"-entrypoint", "/bin/bash", "--", "-c", "printf 'This step output is taken from cache.\n\n'", "printf '200'"},
```

**Comment by drewbutlerbb4** [comment]
Thanks @Tomcli 
I have applied the suggestions from code review
