### PR TITLE
fix(frontend): enhance the when condition UI display

### LINKED ISSUE #372: UI of when condition
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]

This is the UI behavior of when condition, there is one issue here:
Condition2 is not skipped, the skipped one should be flip-again and print-1, could we list flip-again there and mark it is skipped?

image

image

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by fenglixa**
**Which issue is resolved by this Pull Request:** 
Resolves #372

**Description of your changes:**
Make the skipped tasks more accurate in UI display.
 
**Environment tested:**

The flow is more meanful now:

image
image

* Python Version (use `python --version`):
* Tekton Version (use `tkn version`):
* Kubernetes Version (use `kubectl version`):
* OS (e.g. from `/etc/os-release`):

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [x] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

File: frontend/src/lib/WorkflowParser.ts [hunk 1]
```diff
@@ -73,9 +72,29 @@ export default class WorkflowParser {
         statusMap.set(status[taskRunId]['pipelineTaskName'], status[taskRunId]);
     }
 
+    // Add When-condition tasks to conditionTasks Map if it depends on the result of the tasks in statusMap
+    const conditionTasks = new Map<string, any>();
```
Comment (drewbutlerbb4) [inline frontend/src/lib/WorkflowParser.ts:76]: Could we use an array for this instead and just check conditionTasks.includes()? It doesn't seem that the value of the key, value pair ever gets used.

**Review by drewbutlerbb4 — COMMENTED** [review]
Thanks @fenglixa, one question

File: frontend/src/lib/WorkflowParser.ts (hunk 1 above)
Comment (fenglixa) [reply frontend/src/lib/WorkflowParser.ts]: Thanks @drewbutlerbb4 , My initial idea is want to keep the conditionTasks same as statusMap, to avoid anywhere else need the value of the key, but it's true it was not used finally, I modified it based on your comments, please check again. Thanks!

**Comment by drewbutlerbb4** [comment]
/lgtm
Thanks @fenglixa, works great!
